import type { OpenCV } from './opencvLoader';

// The @techstark/opencv-js type definitions (generated by mirada) don't
// declare the video-tracking functions this module uses, even though
// they're present at runtime in the opencv.js build. Extend locally
// rather than casting to `any` at every call site.
type OpenCVVideo = OpenCV & {
  createHanningWindow(dst: InstanceType<OpenCV['Mat']>, size: InstanceType<OpenCV['Size']>, type: number): void;
  phaseCorrelate(
    src1: InstanceType<OpenCV['Mat']>,
    src2: InstanceType<OpenCV['Mat']>,
    window?: InstanceType<OpenCV['Mat']>,
  ): { x: number; y: number };
};

export interface MotionSample {
  /** Estimated shift since the previous sample, in downsampled-frame px. */
  dx: number;
  dy: number;
  /** Magnitude of the shift; used to gate "move slower" guidance. */
  speed: number;
  /** Laplacian-variance sharpness score; higher is sharper. */
  sharpness: number;
  /** 0-1 confidence from phase correlation; low means little texture / lost tracking. */
  trackingConfidence: number;
  /** Mean brightness 0-255, for low-light detection. */
  brightness: number;
  /** Fraction of pixels that are near-saturated (255), for glare detection. */
  glareRatio: number;
  hasPrevious: boolean;
}

export const SAMPLE_WIDTH = 320;

/**
 * Tracks frame-to-frame camera motion using phase correlation (a fast,
 * feature-free technique well suited to running on every live-preview
 * tick) plus a Laplacian-variance sharpness score. This is intentionally
 * cheaper than the ORB/homography pipeline used for final stitching -
 * live tracking only needs "which way and how fast", not pixel-accurate
 * alignment.
 */
export class MotionTracker {
  private readonly cv: OpenCVVideo;
  private prevGray: InstanceType<OpenCV['Mat']> | null = null;
  private readonly hann: InstanceType<OpenCV['Mat']>;
  private readonly sampleHeight: number;

  constructor(cv: OpenCV, aspectRatio: number) {
    this.cv = cv as OpenCVVideo;
    this.sampleHeight = Math.max(2, Math.round(SAMPLE_WIDTH / aspectRatio));
    this.hann = new cv.Mat();
    this.cv.createHanningWindow(this.hann, new cv.Size(SAMPLE_WIDTH, this.sampleHeight), cv.CV_32F);
  }

  reset(): void {
    this.prevGray?.delete();
    this.prevGray = null;
  }

  analyze(source: HTMLCanvasElement): MotionSample {
    const cv = this.cv;
    const full = cv.imread(source);
    const small = new cv.Mat();
    cv.resize(full, small, new cv.Size(SAMPLE_WIDTH, this.sampleHeight), 0, 0, cv.INTER_AREA);
    const gray = new cv.Mat();
    cv.cvtColor(small, gray, cv.COLOR_RGBA2GRAY);
    full.delete();
    small.delete();

    const brightness = cv.mean(gray)[0];
    const glareRatio = this.computeGlareRatio(gray);
    const sharpness = this.computeSharpness(gray);

    let dx = 0;
    let dy = 0;
    let trackingConfidence = 0;
    const hasPrevious = this.prevGray !== null;

    if (this.prevGray) {
      const grayF = new cv.Mat();
      const prevF = new cv.Mat();
      gray.convertTo(grayF, cv.CV_32F);
      this.prevGray.convertTo(prevF, cv.CV_32F);
      try {
        const shift = cv.phaseCorrelate(prevF, grayF, this.hann);
        dx = shift.x;
        dy = shift.y;
        // The JS bindings don't expose phaseCorrelate's peak-response score,
        // so confidence is approximated from image texture (how much signal
        // there was to correlate against) and a sanity check on the shift
        // magnitude - implausibly large shifts usually mean correlation
        // latched onto noise rather than real motion.
        const stddev = new cv.Mat();
        const mean = new cv.Mat();
        cv.meanStdDev(gray, mean, stddev);
        const textureScore = Math.min(1, stddev.data64F[0] / 35);
        mean.delete();
        stddev.delete();
        const maxPlausibleShift = SAMPLE_WIDTH * 0.4;
        const plausibility = Math.max(0, 1 - Math.max(0, Math.hypot(dx, dy) - maxPlausibleShift) / maxPlausibleShift);
        trackingConfidence = Math.min(textureScore, textureScore * 0.5 + plausibility * 0.5);
      } catch {
        trackingConfidence = 0;
      } finally {
        grayF.delete();
        prevF.delete();
      }
    }

    this.prevGray?.delete();
    this.prevGray = gray;

    const speed = Math.hypot(dx, dy);
    return { dx, dy, speed, sharpness, trackingConfidence, brightness, glareRatio, hasPrevious };
  }

  private computeSharpness(gray: InstanceType<OpenCV['Mat']>): number {
    const cv = this.cv;
    const lap = new cv.Mat();
    cv.Laplacian(gray, lap, cv.CV_64F);
    const mean = new cv.Mat();
    const stddev = new cv.Mat();
    cv.meanStdDev(lap, mean, stddev);
    const std = stddev.data64F[0];
    lap.delete();
    mean.delete();
    stddev.delete();
    return std * std;
  }

  private computeGlareRatio(gray: InstanceType<OpenCV['Mat']>): number {
    const cv = this.cv;
    const thresh = new cv.Mat();
    cv.threshold(gray, thresh, 250, 255, cv.THRESH_BINARY);
    const saturated = cv.countNonZero(thresh);
    thresh.delete();
    return saturated / (gray.rows * gray.cols);
  }

  destroy(): void {
    this.prevGray?.delete();
    this.prevGray = null;
    this.hann.delete();
  }
}
